### ISSUE TITLE
Golang snippets

### ISSUE THREAD

**Issue by henrycjchen** [30-seconds/30-seconds-web#114]
is it possible to add golang in this proj

**Comment by Chalarangelo** [comment]
Hello, there are certainly plans to do so in the near future (possibly next quarter). I'll keep this issue open and link to the repo as soon as we get this started, so you can contribute if you want. How does that sound?

**Comment by henrycjchen** [comment]
wonderful!!

**Comment by Chalarangelo** [comment]
As a first step, after starting a repository, we need to work on the reducers/resolvers so that the copied source code and the presented source code can be decoupled. This will allow golang snippets to be presented as 2-spaced on the website, while allowing them to be tab-indented on copy. This might also enable Python snippets to be copied as 4-space-indented, which is the most common style.
