### ISSUE TITLE
Add 30-seconds-of-java

### ISSUE THREAD

**Issue by pawarashish564** [30-seconds/30-seconds-web#130]
You have different section of languages  for 30-seconds of code such as Python , JavaScript . 
I want to add a new section called **Java 8** . See  [my repo](https://github.com/pawarashish564/30seconds-of-Java-8). Can Anyone help me doing that ?

**Comment by Chalarangelo** [comment]
Thanks for the idea. We will consider it. Keeping the issue open to post updates when/if we decide to implement this.

**Comment by pawarashish564** [comment]
Yeah Let me know for the snippets I have collected many java 8 snippets and that can be useful in many scenarios . some of them are very rare but still useful.

**Comment by Chalarangelo** [comment]
As it currently stands, we are taking it slow on adding new languages, especially ones outside our niche (web development). The reason is that languages such as Go and Dart under-perform in every way and we have little to no capacity to keep maintaining them efficiently. 

I am closing the issue on this basis. If we are ever able to handle this and find a reason to, we can reopen it.
