### ISSUE TITLE
Order for cards

### ISSUE THREAD

**Issue by vsemozhetbyt** [30-seconds/30-seconds-web#23]
Previously, in GitHub README.md  or in the site, the snippets were sorted alphabetically. That was handy for casual consecutive reading. Currently, we have only the site with cards in a hardly understandable order. Can the alphabetical order be restored?

**Comment by Chalarangelo** [comment]
Update for anyone interested. We will be delivering sometime later in 2020 Q1, most likely around early March. The expected behavior for this feature are:
- Three order types (`popular`, `alphabetical`, `expertise`).
- Default order will be `popular`.
- All orders will only either ascend or descend and users can fast forward to the last page and browse backwards.
- `popular` will be sorted in descending order. `alphabetical` and `expertise` will be sorted in ascending order.
- `popular` will handle value equality (i.e. same ranking value) by resorting to `alphabetical` order to sort out conflicts.
- `alphabetical` and `expertise` will handle value equality (i.e. same name or same expertise level) by resorting to `popular` order to sort out conflicts.

**Comment by Chalarangelo** [comment]
Starting work on this a little earlier than anticipated, should be able to release before the end of the month, if everything goes according to plan. There might a possible delay if we decide to bundle it up with #64 and #69, but that is yet undecided.

**Comment by Chalarangelo** [comment]
Resolved in 6a4456e.
