### ISSUE TITLE
Breadcrumb for improved navigation

### ISSUE THREAD

**Issue by kgruszczynski** [30-seconds/30-seconds-web#24]
Breadcrumb for improved navigation

**Comment by Chalarangelo** [comment]
We will look into this, as it is something we have been interested in implementing sooner or later. Thanks for the feedback.

As a mental note, we should remember to add structured data to the website for the breadcrumbs.

**Comment by Chalarangelo** [comment]
**Update for anyone interested:** We will be delivering this feature sometime later in 2020 Q1, most likely around early March. 

The expected behavior for this feature as well as related changes are:
- Breadcrumbs will be added to each snippet page, possibly replacing the `Back to ...` link.
- Breadcrumbs will be collapsed on mobile, probably reverting to the existing `Back to ...` link and possibly allowing a way to show appropriate breadcrumbs.
- The `Back to ...` link functionality should be redesigned to allow for personalization (combined with the ordering from #23), but also allowing for a reasonably clear hierarchy between listings and snippets.
- Structured data for breadcrumbs will be added. This will not be personalized, but rather match the hierarchy of `Language > Primary Tag > Snippet`.

**Comment by Chalarangelo** [comment]
### Update

Due to the proposed changes from #57, implementation of this feature will be slightly different:

- The need for category-level breadcrumbs has already been addressed in #71, by introducing category/tag-level anchors that allow navigation from a language's "All" listing to any of its tags and back.
- Snippet-level breadcrumbs provide some value for users looking to navigate back to the previous page, but based on the current designs and proposals from #57, it is yet unclear if the `Back to ...` link will be replaced at this time, entirely removed or converted into a usable breadcrumbs component that will move to the top bar on Desktop and probably take the place of the sliding anchors on mobile. Therefore this feature will be implemented towards the end of [Sprint 3](https://github.com/30-seconds/30-seconds-web/milestone/7) to account for any design changes before that.
- Breadcrumb/`Back to ...` personalization will be automated as part of #23, most likely allowing users to go back to the previous page they were viewing, while having sensible defaults.
- Structured data for breadcrumbs is a priority, as it will improve crawling significantly, so it might even break into its own PR soon.
