### ISSUE TITLE
[BUG] Pretty URLs might not respond

### ISSUE THREAD

**Issue by Trinityyi** [30-seconds/30-seconds-web#49]
## Bug description 

Sometimes, pretty URLs (without trailing `/`) might not respond correctly.

## Steps to reproduce

- Open Chrome Incognito
- Navigate to (https://www.30secondsofcode.org/js/s/pipe-async-functions)
- No response

## Expected behavior

Should respond with the correct page

## Screenshots

![image](https://user-images.githubusercontent.com/13429517/71972648-bd4f1500-3215-11ea-8ffa-f9457e7495ee.png)

## Environment

- Windows 10
- Chrome (Version 76)
- Behind Enterprise Firewall

**Comment by Chalarangelo** [comment]
Thanks for the heads up, @Trinityyi!

I cannot reproduce easily, but it seems that using ugly URLs (with trailing `/`) when linking should fix this. Netlify and Gatsby will redirect the ugly URL to the pretty one anyways, so that's pretty much an easy fix. Added to the current sprint, shouldn't be too hard to fix over the weekend.
